FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
